### PR TITLE
Create pt_br.json + recipe/tag related stuff (WIP)

### PR DESCRIPTION
**Pull request by Brun333rp**
Brazilian Portuguese translations, and other stuff that I aim to do. 

**Edit: Everything is done now**

### CODE REVIEW

**Comment by Brun333rp** [comment]
Do you know why some parts of the translation text are highlited with red? I hope that it doesn't interfer with translations

**Comment by Brun333rp** [comment]
Well, I bet that everything is almost done. Imma get into the remaining things later

**Comment by Xratedjunior** [comment]
Ahh I didn't understand correctly. This is awesome, let me know when you're done

**Comment by Brun333rp** [comment]
It will be hard for me to make the BDB mushrooms usable in Suspicious Stew recipe without breaking it. I think I will not try to change it, so forget what I said previously

**Comment by Brun333rp** [comment]
oh, forgot to say in the last commit: I also added vanilla Turtle Eggs to "forge:eggs" tag, because why not?

**Comment by Brun333rp** [comment]
oof, I commited so many errors! fortunately, I've fixed them

**Comment by Brun333rp** [comment]
well, I think that everything I had to do is done. I will keep it as a draft for a while, and if I don't find more things to do then I will mark it as ready to review.

**Comment by Brun333rp** [comment]
The pull request is complete

**Comment by Brun333rp** [comment]
WAIT, THERE IS SOMETHING I CAN DO

**Comment by Brun333rp** [comment]
now it's actually done

**Comment by Xratedjunior** [comment]
This is cool! I will try to conclude everything in the next update

**Comment by Brun333rp** [comment]
I think you could simply merge this pull request

**Comment by Brun333rp** [comment]
I have find more things to do

**Comment by Brun333rp** [comment]
Also added BDB mushrooms into "farmersdelight:compost_activators" tag

**Comment by Xratedjunior** [comment]
Yeahh but I'm just gonna make sure

**Comment by Xratedjunior** [comment]
I've reviewed 78 out of 87 files at the moment. Getting there :)

**Pull request closed without merging**
